// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZSCLQo7G4D4AvjTtfPHFNVPAGnGThq7U',
    appId: '1:457342149062:web:cfd74026ad16c9de6ad2c7',
    messagingSenderId: '457342149062',
    projectId: 'hope-5479b',
    authDomain: 'hope-5479b.firebaseapp.com',
    storageBucket: 'hope-5479b.appspot.com',
    measurementId: 'G-FWHR0KT686',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJ7xK8V8kk2NVD7fJQUkOYfFvkE52BQ0',
    appId: '1:457342149062:android:71cfffc370ad9ba56ad2c7',
    messagingSenderId: '457342149062',
    projectId: 'hope-5479b',
    storageBucket: 'hope-5479b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_F7FPHy5ds1k1VEMoIxu5OkVzkVn9A4c',
    appId: '1:457342149062:ios:dc4d5a8f26b6699f6ad2c7',
    messagingSenderId: '457342149062',
    projectId: 'hope-5479b',
    storageBucket: 'hope-5479b.appspot.com',
    iosClientId: '457342149062-3ja7qrh5khe1jh2bkoiejm0tll0cevu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_F7FPHy5ds1k1VEMoIxu5OkVzkVn9A4c',
    appId: '1:457342149062:ios:0b41578de31446f56ad2c7',
    messagingSenderId: '457342149062',
    projectId: 'hope-5479b',
    storageBucket: 'hope-5479b.appspot.com',
    iosClientId: '457342149062-aq6t68ac56ebmlsombj8ram4n2qphf52.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeBuilder.RunnerTests',
  );
}
